import { STAT_KEYS } from "../../stats/statKeys";
import type { CardDef } from "../../stats/modifierTypes";

export const MECHANICS_CARDS_V1: CardDef[] = [
  {
    id: "CARD_PIERCE_1",
    isEnabled: true,
    displayName: "+1 pierce",
    rarity: 4,
    powerTier: 3,
    tags: ["pierce"],
    mods: [{ key: STAT_KEYS.PIERCE_ADD, op: "add", value: 1 }],
  },
  {
    id: "CARD_PIERCE_2",
    isEnabled: true,
    displayName: "+2 pierce",
    rarity: 4,
    powerTier: 4,
    tags: ["pierce"],
    mods: [{ key: STAT_KEYS.PIERCE_ADD, op: "add", value: 2 }],
  },
  {
    id: "CARD_PROJECTILE_1",
    isEnabled: true,
    displayName: "+1 projectile",
    rarity: 4,
    powerTier: 3,
    tags: ["projectiles"],
    mods: [{ key: STAT_KEYS.PROJECTILES_ADD, op: "add", value: 1 }],
  },
  {
    id: "CARD_PROJECTILE_2",
    isEnabled: true,
    displayName: "+2 projectile",
    rarity: 4,
    powerTier: 4,
    tags: ["projectiles"],
    mods: [{ key: STAT_KEYS.PROJECTILES_ADD, op: "add", value: 2 }],
  },
  {
    id: "CARD_POISON_INCREASED_30",
    isEnabled: true,
    displayName: "+30% increased poison damage",
    rarity: 2,
    powerTier: 2,
    tags: ["poison", "dot"],
    mods: [{ key: STAT_KEYS.DOT_POISON_DAMAGE_INCREASED, op: "increased", value: 0.30 }],
  },
  {
    id: "CARD_IGNITE_INCREASED_30",
    isEnabled: true,
    displayName: "+30% increased ignite damage",
    rarity: 2,
    powerTier: 2,
    tags: ["ignite", "dot"],
    mods: [{ key: STAT_KEYS.DOT_IGNITE_DAMAGE_INCREASED, op: "increased", value: 0.30 }],
  },
  {
    id: "CARD_DOT_DURATION_25",
    isEnabled: true,
    displayName: "+25% increased damage over time duration",
    rarity: 2,
    powerTier: 2,
    tags: ["dot"],
    mods: [{ key: STAT_KEYS.DOT_DURATION_INCREASED, op: "increased", value: 0.25 }],
  },
  {
    id: "CARD_DOT_TICK_RATE_MORE_20",
    isEnabled: true,
    displayName: "Damage over time ticks 20% more frequently",
    rarity: 3,
    powerTier: 3,
    tags: ["dot"],
    mods: [{ key: STAT_KEYS.DOT_TICK_RATE_MORE, op: "more", value: 0.20 }],
  },
];
