import type { BuildingPackId, BuildingSkin, BuildingSkinId } from "./structureSkins";

export const CONTAINER_PACK_ID: BuildingPackId = "containers";

export const CONTAINER_SKINS: Record<BuildingSkinId, BuildingSkin> = {
    container1: {
        id: "container1",
        w: 2,
        h: 3,
        heightUnits: 8,
        anchorLiftUnits: 0,
        wallLiftUnits: 0,
        roofLiftPx: -40,
        spriteScale: 1.02,
        roof: "structures/containers/1/top",
        wallSouth: [
            "structures/containers/1/s_1",
            "structures/containers/1/s_2",
        ],
        wallEast: [
            "structures/containers/1/e_1",
            "structures/containers/1/e_2",
            "structures/containers/1/e_3",
        ],
    },
    container_dark_blue: {
        id: "container_dark_blue",
        w: 2,
        h: 3,
        heightUnits: 8,
        anchorLiftUnits: 0,
        wallLiftUnits: 0,
        roofLiftPx: -40,
        spriteScale: 1.02,
        roof: "structures/containers/dark_blue/1/top",
        wallSouth: [
            "structures/containers/dark_blue/1/s_1",
            "structures/containers/dark_blue/1/s_2",
        ],
        wallEast: [
            "structures/containers/dark_blue/1/e_1",
            "structures/containers/dark_blue/1/e_2",
            "structures/containers/dark_blue/1/e_3",
        ],
    },
    container_dark_blue_flipped: {
        id: "container_dark_blue_flipped",
        w: 3,
        h: 2,
        heightUnits: 8,
        anchorLiftUnits: 0,
        wallLiftUnits: 0,
        roofLiftPx: -40,
        spriteScale: 1.02,
        roof: "structures/containers/dark_blue_flipped/1/top",
        wallSouth: [
            "structures/containers/dark_blue_flipped/1/s_1",
            "structures/containers/dark_blue_flipped/1/s_2",
        ],
        wallEast: [
            "structures/containers/dark_blue_flipped/1/e_1",
            "structures/containers/dark_blue_flipped/1/e_2",
            "structures/containers/dark_blue_flipped/1/e_3",
        ],
    },
    container_green: {
        id: "container_green",
        w: 2,
        h: 3,
        heightUnits: 8,
        anchorLiftUnits: 0,
        wallLiftUnits: 0,
        roofLiftPx: -40,
        spriteScale: 1.02,
        roof: "structures/containers/green/1/top",
        wallSouth: [
            "structures/containers/green/1/s_1",
            "structures/containers/green/1/s_2",
        ],
        wallEast: [
            "structures/containers/green/1/e_1",
            "structures/containers/green/1/e_2",
            "structures/containers/green/1/e_3",
        ],
    },
    container_green_flipped: {
        id: "container_green_flipped",
        w: 3,
        h: 2,
        heightUnits: 8,
        anchorLiftUnits: 0,
        wallLiftUnits: 0,
        roofLiftPx: -40,
        spriteScale: 1.02,
        roof: "structures/containers/green_flipped/1/top",
        wallSouth: [
            "structures/containers/green_flipped/1/s_1",
            "structures/containers/green_flipped/1/s_2",
        ],
        wallEast: [
            "structures/containers/green_flipped/1/e_1",
            "structures/containers/green_flipped/1/e_2",
            "structures/containers/green_flipped/1/e_3",
        ],
    },
    container_light_blue: {
        id: "container_light_blue",
        w: 2,
        h: 3,
        heightUnits: 8,
        anchorLiftUnits: 0,
        wallLiftUnits: 0,
        roofLiftPx: -40,
        spriteScale: 1.02,
        roof: "structures/containers/light_blue/1/top",
        wallSouth: [
            "structures/containers/light_blue/1/s_1",
            "structures/containers/light_blue/1/s_2",
        ],
        wallEast: [
            "structures/containers/light_blue/1/e_1",
            "structures/containers/light_blue/1/e_2",
            "structures/containers/light_blue/1/e_3",
        ],
    },
    container_light_blue_flipped: {
        id: "container_light_blue_flipped",
        w: 3,
        h: 2,
        heightUnits: 8,
        anchorLiftUnits: 0,
        wallLiftUnits: 0,
        roofLiftPx: -40,
        spriteScale: 1.02,
        roof: "structures/containers/light_blue_flipped/1/top",
        wallSouth: [
            "structures/containers/light_blue_flipped/1/s_1",
            "structures/containers/light_blue_flipped/1/s_2",
        ],
        wallEast: [
            "structures/containers/light_blue_flipped/1/e_1",
            "structures/containers/light_blue_flipped/1/e_2",
            "structures/containers/light_blue_flipped/1/e_3",
        ],
    },
    container_red: {
        id: "container_red",
        w: 2,
        h: 3,
        heightUnits: 8,
        anchorLiftUnits: 0,
        wallLiftUnits: 0,
        roofLiftPx: -40,
        spriteScale: 1.02,
        roof: "structures/containers/red/1/top",
        wallSouth: [
            "structures/containers/red/1/s_1",
            "structures/containers/red/1/s_2",
        ],
        wallEast: [
            "structures/containers/red/1/e_1",
            "structures/containers/red/1/e_2",
            "structures/containers/red/1/e_3",
        ],
    },
    container_red_flipped: {
        id: "container_red_flipped",
        w: 3,
        h: 2,
        heightUnits: 8,
        anchorLiftUnits: 0,
        wallLiftUnits: 0,
        roofLiftPx: -40,
        spriteScale: 1.02,
        roof: "structures/containers/red_flipped/1/top",
        wallSouth: [
            "structures/containers/red_flipped/1/s_1",
            "structures/containers/red_flipped/1/s_2",
        ],
        wallEast: [
            "structures/containers/red_flipped/1/e_1",
            "structures/containers/red_flipped/1/e_2",
            "structures/containers/red_flipped/1/e_3",
        ],
    },
};

export const CONTAINER_PACKS: Record<BuildingPackId, BuildingSkinId[]> = {
    [CONTAINER_PACK_ID]: [
        "container1",
        "container_dark_blue",
        "container_dark_blue_flipped",
        "container_green",
        "container_green_flipped",
        "container_light_blue",
        "container_light_blue_flipped",
        "container_red",
        "container_red_flipped",
    ],
};
