// src/game/math/index.ts
//
// Re-exports all 3D math types and utilities for the layered 3D map system.

// Vector3D
export {
    type Vector3D,
    V3_ZERO,
    V3_ONE,
    V3_UP,
    V3_DOWN,
    V3_FORWARD,
    V3_BACK,
    V3_RIGHT,
    V3_LEFT,
    v3,
    v3From2D,
    v3Copy,
    v3Add,
    v3Sub,
    v3Mul,
    v3Div,
    v3Neg,
    v3MulComp,
    v3DivComp,
    v3Dot,
    v3Cross,
    v3Mag,
    v3MagSq,
    v3Normalize,
    v3Dist,
    v3DistSq,
    v3DistXY,
    v3DistXYSq,
    v3Lerp,
    v3MoveTowards,
    v3Clamp,
    v3ToXY,
    v3Approx,
    v3ToString,
    v3RotateZ,
    v3AngleXY,
    v3Min,
    v3Max,
    v3Abs,
    v3Floor,
    v3Ceil,
    v3Round,
} from "./Vector3D";

// BoundingBox3D
export {
    type BoundingBox3D,
    bb3,
    bb3FromCenter,
    bb3FromCenterSize,
    bb3FromPoint,
    bb3FromCircle,
    bb3Center,
    bb3Size,
    bb3HalfExtents,
    bb3Width,
    bb3Depth,
    bb3Height,
    bb3Volume,
    bb3Intersects,
    bb3IntersectsXY,
    bb3ContainsPoint,
    bb3ContainsBox,
    bb3Penetration,
    bb3ClosestPoint,
    bb3SignedDistance,
    bb3Translate,
    bb3Scale,
    bb3Expand,
    bb3ExpandV,
    bb3Union,
    bb3Intersection,
    bb3RayIntersect,
    bb3IsValid,
    bb3Corners,
    bb3ToString,
} from "./BoundingBox3D";

// Entity3D
export {
    type Entity3DProps,
    type CollisionResult3D,
    entity3DBounds,
    entity3DBoundsFromSoA,
    entities3DCollide,
    entity3DContainsPoint,
    entity3DOnFloor,
    entities3DSameFloor,
    entity3DSeparationXY,
    entity3DCollisionResolve,
    applyGravity,
    isGrounded,
    clampToGround,
    entity3DDistXY,
    entity3DDist,
    entity3DDirectionXY,
    entity3DDirection,
    extractEntity3D,
    checkSoACollision3D,
    inRange3D,
    inRangeXY,
} from "./Entity3D";
